// src/main/services/context_compressor.ts
// Deterministic context compression for free-chat sessions — no LLM required.
//
// When Claude Code reports "Prompt too long" after a --resume, the caller
// compresses task.thread and retries without --resume, injecting the
// condensed history into the system prompt instead.
//
// Compression rules (in priority order):
//   1. Tool messages (role='tool') with re-fetchable results:
//      replace result with a short reference string.
//   2. Remaining long message texts: hard-truncate to MESSAGE_MAX_CHARS.
//   3. User/agent/system messages below threshold: kept verbatim.
//
// "Re-fetchable" tools are those whose output can be regenerated by calling
// the tool again (Read, Grep, Glob, Bash, WebFetch, WebSearch). Tool results
// whose content cannot be recovered (e.g. Edit, Write confirmations) are
// kept verbatim — truncated only if very long.

import type { AgentMessage, ToolCall } from '../../core/domain/agent';

// ---------------------------------------------------------------------------
// Tuning constants
// ---------------------------------------------------------------------------

/** Tool result text longer than this is replaced with a reference. */
const TOOL_RESULT_REF_THRESHOLD = 1_500;

/** Any message text longer than this is hard-truncated. */
const MESSAGE_TEXT_MAX = 6_000;

/** Tools whose results can be regenerated by re-calling the tool. */
const REFETCHABLE = new Set([
  'Read', 'Glob', 'Grep', 'Bash', 'LS',
  'WebFetch', 'WebSearch',
  'NotebookRead',
]);

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export interface CompressResult {
  /** Condensed messages, suitable for embedding in a system prompt. */
  readonly lines: readonly string[];
  /** Number of messages where content was replaced with a reference. */
  readonly compressedCount: number;
  /** Characters saved vs the original thread serialised naively. */
  readonly savedChars: number;
}

/**
 * Compress an agent-message thread deterministically.
 * Returns a flat array of human-readable lines for embedding in a prompt.
 *
 * Pass `thread` sliced to exclude the current user message — that message
 * is sent separately via `session.send()` and must not appear twice.
 */
export function compressThread(thread: readonly AgentMessage[]): CompressResult {
  let compressedCount = 0;
  let savedChars = 0;
  const lines: string[] = [];

  for (const msg of thread) {
    const { text, compressed, saved } = compressMessage(msg);
    if (compressed) {
      compressedCount++;
      savedChars += saved;
    }
    lines.push(`[${roleLabel(msg.role)}] ${text}`);
  }

  return { lines, compressedCount, savedChars };
}

/** Format the compressed thread for insertion into a system prompt. */
export function formatForSystemPrompt(result: CompressResult): string {
  return result.lines.join('\n\n');
}

/**
 * System-prompt preamble that explains the restored context to the agent.
 * Appended BEFORE the formatted history so the agent reads it first.
 */
export const CONTEXT_RESTORED_NOTICE = `
[CONTEXT RESTORED] The conversation history was too long to resume directly. \
Some tool results (Read, Bash, Grep, etc.) have been replaced with short \
references like "[Tool: Read("path") — content truncated]". If you need the \
full content, call the tool again. All user messages and your own responses \
are preserved verbatim.
`.trim();

/**
 * Returns true if the error string matches known "context too long" patterns
 * from Claude Code / Anthropic API.
 */
export function isContextTooLongError(err: unknown): boolean {
  const msg = errorMessage(err).toLowerCase();
  return (
    msg.includes('prompt too long') ||
    msg.includes('context window') ||
    msg.includes('too many tokens') ||
    msg.includes('context_window_exceeded') ||
    msg.includes('input too long') ||
    msg.includes('max_tokens') ||
    msg.includes('token limit')
  );
}

// ---------------------------------------------------------------------------
// Internals
// ---------------------------------------------------------------------------

interface MsgResult {
  text: string;
  compressed: boolean;
  saved: number;
}

function compressMessage(msg: AgentMessage): MsgResult {
  // Tool messages with a ToolCall attached — prime compression candidates.
  if (msg.role === 'tool' && msg.toolCall) {
    return compressToolMessage(msg.toolCall, msg.text);
  }

  // Other messages: truncate if very long.
  if (msg.text.length > MESSAGE_TEXT_MAX) {
    const saved = msg.text.length - MESSAGE_TEXT_MAX;
    return {
      text: msg.text.slice(0, MESSAGE_TEXT_MAX) + '\n[… truncated]',
      compressed: true,
      saved,
    };
  }

  return { text: msg.text, compressed: false, saved: 0 };
}

function compressToolMessage(tc: ToolCall, originalText: string): MsgResult {
  const result = tc.result ?? '';

  if (REFETCHABLE.has(tc.name) && result.length > TOOL_RESULT_REF_THRESHOLD) {
    const ref = buildRef(tc);
    const saved = originalText.length - ref.length;
    return { text: ref, compressed: true, saved: Math.max(0, saved) };
  }

  // Not re-fetchable or short enough — truncate only if very long.
  if (originalText.length > MESSAGE_TEXT_MAX) {
    const saved = originalText.length - MESSAGE_TEXT_MAX;
    return {
      text: originalText.slice(0, MESSAGE_TEXT_MAX) + '\n[… truncated]',
      compressed: true,
      saved,
    };
  }

  return { text: originalText, compressed: false, saved: 0 };
}

function buildRef(tc: ToolCall): string {
  const argStr = describeArgs(tc.name, tc.args);
  return `[Tool: ${tc.name}(${argStr}) — content truncated, re-run tool if needed]`;
}

function describeArgs(name: string, args: Record<string, unknown>): string {
  switch (name) {
    case 'Read':
      return `"${args.file_path ?? args.path ?? ''}"`;
    case 'Glob':
      return `pattern="${args.pattern ?? ''}"`;
    case 'Grep':
      return `"${args.pattern ?? ''}"${args.path ? ` in ${args.path}` : ''}`;
    case 'Bash':
    case 'LS': {
      const cmd = typeof args.command === 'string' ? args.command : '';
      return `"${cmd.length > 80 ? cmd.slice(0, 80) + '…' : cmd}"`;
    }
    case 'WebFetch':
      return `"${args.url ?? ''}"`;
    case 'WebSearch':
      return `"${args.query ?? ''}"`;
    case 'NotebookRead':
      return `"${args.notebook_path ?? ''}"`;
    default: {
      const keys = Object.keys(args).slice(0, 3);
      return keys.map((k) => `${k}="${String(args[k]).slice(0, 40)}"`).join(', ');
    }
  }
}

function roleLabel(role: string): string {
  switch (role) {
    case 'user':   return 'User';
    case 'agent':  return 'Assistant';
    case 'system': return 'System';
    case 'tool':   return 'Tool';
    default:       return role;
  }
}

function errorMessage(err: unknown): string {
  if (err instanceof Error) return err.message;
  return String(err);
}
