/**
 * Screenshot comparator for Sherpa UI visual regression harness.
 *
 * Pure Node.js module. Decodes PNG buffers via pngjs into raw RGBA pixel
 * arrays, then runs Structural Similarity Index (SSIM) via ssim.js.
 *
 * Per-screen thresholds are loaded from `tests/visual/thresholds.json`,
 * which is generated by `calibrate-thresholds.ts`. The threshold can also
 * be passed explicitly via the `threshold` argument (overrides the JSON
 * lookup), which is handy for self-tests.
 *
 * Threshold semantics: SSIM is in [-1, 1], where 1.0 = identical. The
 * comparator returns `pass: ssim >= threshold`.
 */

import { readFileSync, existsSync } from 'node:fs';
import { resolve, dirname, basename, extname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { PNG } from 'pngjs';
import { ssim } from 'ssim.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const THRESHOLDS_JSON = resolve(__dirname, 'thresholds.json');

export type ScreenName =
  | 'welcome'
  | 'workspace'
  | 'agent_panel'
  | 'kanban'
  | 'settings'
  | 'metrics'
  | 'recovery';

export const SCREEN_NAMES: readonly ScreenName[] = [
  'welcome',
  'workspace',
  'agent_panel',
  'kanban',
  'settings',
  'metrics',
  'recovery'
] as const;

export type CompareResult = {
  /** SSIM mean (mssim) score in approx. [-1, 1]; 1.0 = identical. */
  ssim: number;
  /** True if ssim >= threshold. */
  pass: boolean;
  /** The threshold that was applied. */
  threshold: number;
};

export type ImageInput = string | Buffer;

/**
 * Decode a PNG (Buffer or filesystem path) into the ImageData shape ssim.js
 * expects: { data: Uint8ClampedArray (RGBA), width, height }.
 */
export function decodePng(input: ImageInput): { data: Uint8ClampedArray; width: number; height: number } {
  const buf = Buffer.isBuffer(input) ? input : readFileSync(input);
  const png = PNG.sync.read(buf);
  // pngjs returns an RGBA Uint8Array with 4 bytes per pixel for non-palette images.
  // ssim.js expects Uint8ClampedArray; wrap without copying.
  const data = new Uint8ClampedArray(png.data.buffer, png.data.byteOffset, png.data.byteLength);
  return { data, width: png.width, height: png.height };
}

/**
 * Look up the per-screen threshold for a given baseline path.
 * Falls back to 0.85 (the AC-3 floor) if thresholds.json is missing or
 * the screen name is not present.
 */
export function thresholdFor(screen: string): number {
  if (!existsSync(THRESHOLDS_JSON)) {
    return 0.85;
  }
  let parsed: Record<string, number>;
  try {
    parsed = JSON.parse(readFileSync(THRESHOLDS_JSON, 'utf8')) as Record<string, number>;
  } catch {
    return 0.85;
  }
  const value = parsed[screen];
  if (typeof value === 'number' && Number.isFinite(value) && value >= 0.85 && value <= 0.99) {
    return value;
  }
  return 0.85;
}

/**
 * Infer a screen name from a baseline path or label, e.g.
 *   tests/visual/baselines/welcome.png -> "welcome"
 *   "welcome" -> "welcome"
 */
export function inferScreenName(label: string): string {
  const base = basename(label, extname(label));
  return base;
}

/**
 * Compare two PNG images via SSIM.
 *
 * @param baseline    PNG path or Buffer.
 * @param candidate   PNG path or Buffer.
 * @param thresholdOrScreen  If number — used directly as threshold.
 *                           If string — looked up in thresholds.json.
 *                           If undefined — screen inferred from baseline path.
 */
export async function compareScreenshots(
  baseline: ImageInput,
  candidate: ImageInput,
  thresholdOrScreen?: number | string
): Promise<CompareResult> {
  const a = decodePng(baseline);
  const b = decodePng(candidate);

  if (a.width !== b.width || a.height !== b.height) {
    return {
      ssim: 0,
      pass: false,
      threshold: typeof thresholdOrScreen === 'number' ? thresholdOrScreen : 0.85
    };
  }

  let threshold: number;
  if (typeof thresholdOrScreen === 'number') {
    threshold = thresholdOrScreen;
  } else if (typeof thresholdOrScreen === 'string') {
    threshold = thresholdFor(thresholdOrScreen);
  } else {
    const screen = typeof baseline === 'string' ? inferScreenName(baseline) : 'unknown';
    threshold = thresholdFor(screen);
  }

  const result = ssim(a, b, { ssim: 'fast' });
  const score = result.mssim;
  return {
    ssim: score,
    pass: score >= threshold,
    threshold
  };
}
